from std.testing import assert_equal, assert_true, assert_raises, TestSuite
from mcrypto.compression.algorithm import (
    CompressionTransform,
    parse_compression_transform,
)
from mcrypto.compression.transforms import transform, deflate, inflate


def _corpus() -> List[List[UInt8]]:
    var empty = List[UInt8]()
    var repeated = List[UInt8](length=4096, fill=0xA5)
    var sequence = List[UInt8](capacity=8192)
    for i in range(8192):
        sequence.append(UInt8(i & 255))
    var mixed = List[UInt8](capacity=6000)
    for i in range(6000):
        mixed.append(UInt8((i * 73 + (i // 7) * 19) & 255))
    return [empty^, repeated^, sequence^, mixed^]


def test_roundtrip_corpus() raises:
    var corpus = _corpus()
    for message in corpus:
        var raw = deflate(Span(message))
        assert_equal(inflate(Span(raw)), message)
        for compressor, decompressor in [
            (
                CompressionTransform.ZLIB_COMPRESS,
                CompressionTransform.ZLIB_DECOMPRESS,
            ),
            (CompressionTransform.GZIP, CompressionTransform.GUNZIP),
        ]:
            var encoded = transform(compressor, Span(message))
            assert_equal(transform(decompressor, Span(encoded)), message)
    var compressible = List[UInt8](length=4096, fill=7)
    assert_true(len(deflate(Span(compressible))) < 100)


def test_dynamic_and_fixed_vectors() raises:
    # Python zlib output using RFC 1951 dynamic Huffman coding.
    var raw: List[UInt8] = [
        237,
        205,
        193,
        13,
        3,
        33,
        12,
        68,
        209,
        86,
        166,
        128,
        40,
        149,
        108,
        19,
        14,
        182,
        86,
        150,
        48,
        176,
        96,
        250,
        15,
        82,
        154,
        200,
        97,
        206,
        163,
        63,
        239,
        234,
        211,
        2,
        62,
        214,
        14,
        104,
        175,
        125,
        98,
        121,
        66,
        194,
        242,
        133,
        210,
        219,
        178,
        146,
        150,
        123,
        66,
        212,
        135,
        175,
        226,
        237,
        134,
        85,
        63,
        227,
        50,
        61,
        1,
        204,
        247,
        138,
        174,
        72,
        139,
        113,
        98,
        111,
        197,
        213,
        117,
        183,
        196,
        78,
        84,
        249,
        156,
        123,
        88,
        254,
        174,
        13,
        33,
        119,
        19,
        72,
        245,
        103,
        203,
        27,
        23,
        109,
        218,
        180,
        105,
        211,
        166,
        77,
        155,
        54,
        109,
        218,
        180,
        105,
        211,
        166,
        77,
        155,
        54,
        109,
        218,
        180,
        105,
        211,
        166,
        77,
        251,
        175,
        236,
        47,
    ]
    var expected = List[UInt8]()
    for _ in range(50):
        for (
            byte
        ) in "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ".as_bytes():
            expected.append(byte)
    assert_equal(inflate(Span(raw)), expected)
    # RFC 1951 stored block carrying "hello".
    var stored: List[UInt8] = [1, 5, 0, 250, 255, 104, 101, 108, 108, 111]
    assert_equal(inflate(Span(stored)), List("hello".as_bytes()))
    # RFC 1950 zlib stream generated by zlib for "hello".
    var zlib_vector: List[UInt8] = [
        120,
        156,
        203,
        72,
        205,
        201,
        201,
        7,
        0,
        6,
        44,
        2,
        21,
    ]
    assert_equal(
        transform(CompressionTransform.ZLIB_DECOMPRESS, Span(zlib_vector)),
        List("hello".as_bytes()),
    )
    # Deterministic RFC 1952-compatible gzip member generated by Python gzip.
    var gz: List[UInt8] = [
        31,
        139,
        8,
        0,
        0,
        0,
        0,
        0,
        2,
        255,
        203,
        72,
        205,
        201,
        201,
        7,
        0,
        134,
        166,
        16,
        54,
        5,
        0,
        0,
        0,
    ]
    assert_equal(
        transform(CompressionTransform.GUNZIP, Span(gz)),
        List("hello".as_bytes()),
    )


def test_concatenated_gzip_members() raises:
    var left = transform(CompressionTransform.GZIP, "hello ".as_bytes())
    var right = transform(CompressionTransform.GZIP, "world".as_bytes())
    for byte in right:
        left.append(byte)
    assert_equal(
        transform(CompressionTransform.GUNZIP, Span(left)),
        List("hello world".as_bytes()),
    )


def test_validation_errors() raises:
    var payload = List("checksum validation".as_bytes())
    var z = transform(CompressionTransform.ZLIB_COMPRESS, Span(payload))
    z[len(z) - 1] ^= 1
    with assert_raises():
        _ = transform(CompressionTransform.ZLIB_DECOMPRESS, Span(z))
    var g = transform(CompressionTransform.GZIP, Span(payload))
    g[len(g) - 8] ^= 1
    with assert_raises():
        _ = transform(CompressionTransform.GUNZIP, Span(g))
    var truncated = transform(CompressionTransform.GZIP, Span(payload))
    _ = truncated.pop()
    with assert_raises():
        _ = transform(CompressionTransform.GUNZIP, Span(truncated))
    var invalid_stored: List[UInt8] = [1, 1, 0, 0, 0, 65]
    with assert_raises():
        _ = inflate(Span(invalid_stored))
    with assert_raises():
        _ = parse_compression_transform("unknown")


def main() raises:
    TestSuite.discover_tests[__functions_in_module()]().run()
